# Generated by Django 4.2.1 on 2023-09-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("loan_app", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="LoanApplication2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("applicant_name", models.CharField(max_length=100)),
                ("business_name", models.CharField(max_length=100)),
                (
                    "requested_loan_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("has_profit_last_12_months", models.BooleanField()),
                (
                    "average_asset_value",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("pre_assessment", models.IntegerField(default=20)),
            ],
        ),
        migrations.RemoveField(
            model_name="loanapplication", name="average_asset_value"
        ),
        migrations.RemoveField(
            model_name="loanapplication", name="has_profit_last_12_months"
        ),
        migrations.AddField(
            model_name="loanapplication",
            name="year_established",
            field=models.PositiveIntegerField(default=None),
        ),
        migrations.CreateModel(
            name="BalanceSheetEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "profit_or_loss",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("assets_value", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "loan_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="loan_app.loanapplication",
                    ),
                ),
            ],
        ),
    ]
