# Generated by Django 4.2.1 on 2023-09-02 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("loan_app", "0002_loanapplication2_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loanapplication",
            name="applicant_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        )
    ]
