# Generated by Django 4.2.1 on 2023-09-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("loan_app", "0003_alter_loanapplication_applicant_name")]

    operations = [
        migrations.RenameField(
            model_name="loanapplication", old_name="applicant_name", new_name="user"
        ),
        migrations.RenameField(
            model_name="loanapplication2", old_name="applicant_name", new_name="user"
        ),
    ]
